name: check-source

on:
  workflow_call:
    secrets:
      BOT_APP_ID:
        required: true
      BOT_PRIVATE_KEY:
        required: true

permissions:
  contents: read
  id-token: write
  packages: write

defaults:
  run:
    shell: bash

env:
  GOPRIIVATE: github.com/chinesecheckers/*

jobs:

  docker-build:
    uses: ./.github/workflows/docker-build.yml
    with:
      PUSH: false
    secrets: inherit
