name: detect-changes

on:
  workflow_call:
    outputs:
      source-changed:
        value: ${{ jobs.detect-changes.outputs.source-changed }}
      ci-changed:
        value: ${{ jobs.detect-changes.outputs.ci-changed }}

permissions:
  contents: read
  pull-requests: write

defaults:
  run:
    shell: bash

jobs:
  
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      source-changed: ${{ contains(fromJson(steps.changed-paths.outputs.changes || '[]'), 'source') }}
      ci-changed: ${{ contains(fromJson(steps.changed-paths.outputs.changes || '[]'), 'ci') }}
    steps:
      -
        uses: actions/checkout@v5
      -
        name: Check for changes
        uses: dorny/paths-filter@v3
        id: changed-paths
        with:
          filters: |
            source:
              - 'docker-quicktype/**'
            ci:
              - '.github/**'
              - '.gitignore'
              - 'Makefile'
              - 'scripts/**'
      -
        name: Update PR labels
        if: github.event_name == 'pull_request'
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: |
            ${{ steps.changed-paths.outputs.ci == 'true' && 'ci' || '' }}
