name: docker-build

on:
  workflow_call:
    inputs:
      PUSH:
        required: true
        type: boolean
    secrets:
      BOT_APP_ID:
        required: true
      BOT_PRIVATE_KEY:
        required: true

permissions: write-all

defaults:
  run:
    shell: bash

env:
  GOPRIIVATE: github.com/chinesecheckers/*

jobs:

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Generate bot token
        id: bot-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}
      -
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      -
        id: check-versions
        name: Check node versions
        working-directory: docker-quicktype
        run: |
          CURRENT_NODE_VERSION="$(cat .nvmrc)"
          echo "current-node-version=$CURRENT_NODE_VERSION" | tee -a "$GITHUB_OUTPUT"

          # Parse the Dockerfile to get the Node.js version
          DOCKER_NODE_VERSION=v$(cat Dockerfile \
              | grep 'FROM node:' \
              | head -n 1 \
              | sed -E 's/FROM node:([^ ]+).*/\1/')

          echo "docker-node-version=$DOCKER_NODE_VERSION" | tee -a "$GITHUB_OUTPUT"

          if [[ "$CURRENT_NODE_VERSION" == "$DOCKER_NODE_VERSION" ]]; then
              echo "Node version is already up to date."
              echo "needs-update=false" >> $GITHUB_OUTPUT
          else
              echo "Node version needs to be updated."
              echo "needs-update=true" >> $GITHUB_OUTPUT
          fi
      -
        uses: actions/setup-node@v5
        if: steps.check-versions.outputs.needs-update == 'true'
        with:
          node-version: ${{ steps.check-versions.outputs.docker-node-version }}
          cache: npm
          cache-dependency-path: docker-quicktype/package-lock.json
      -
        name: Update project Node version
        if: steps.check-versions.outputs.needs-update == 'true'
        working-directory: docker-quicktype
        env:
          TARGET_VERSION: ${{ steps.check-versions.outputs.docker-node-version }}
        run: |
          echo "${TARGET_VERSION}" > .nvmrc
          npm i
      -
        name: Generate examples
        if: steps.check-versions.outputs.needs-update == 'true'
        working-directory: examples
        run: |
          make generate
      -
        name: Detect changes
        id: detect-changes
        run: |
          git status -s

          if [ -n "$(git status -s)" ]; then
            echo "detected=true" | tee -a "$GITHUB_OUTPUT"
          else
            echo "detected=false" | tee -a "$GITHUB_OUTPUT"
          fi
      -
        name: Commit changes if detected
        if: ${{ steps.detect-changes.outputs.detected == 'true' }}
        uses: planetscale/ghcommit-action@v0.2.17
        env:
          GITHUB_TOKEN: ${{ steps.bot-token.outputs.token }}
        with:
          commit_message: "🤖 use node ${{ steps.check-versions.outputs.docker-node-version }}"
          repo: ${{ github.repository }}
          branch: ${{ github.head_ref || github.ref_name }}
      -
        name: Fail if changes
        if: ${{ steps.detect-changes.outputs.detected == 'true' }}
        run: exit 1
      -
        uses: docker/setup-buildx-action@v3
      -
        if: ${{ inputs.PUSH }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/quicktype
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=pr
      -
        uses: docker/build-push-action@v6
        with:
          context: ./docker-quicktype
          push: ${{ inputs.PUSH }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
