name: docker-build

on:
  workflow_call:
    inputs:
      PUSH:
        required: true
        type: boolean
    secrets:
      BOT_APP_ID:
        required: true
      BOT_PRIVATE_KEY:
        required: true

permissions: write-all

defaults:
  run:
    shell: bash

env:
  GOPRIIVATE: github.com/chinesecheckers/*

jobs:

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Generate bot token
        id: bot-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}
      -
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      -
        id: check-versions
        if: github.event_name == 'pull_request'
        name: Check node versions
        working-directory: docker-quicktype
        run: |
          CURRENT_NODE_VERSION="$(cat .nvmrc)"
          echo "current-node-version=$CURRENT_NODE_VERSION" | tee -a "$GITHUB_OUTPUT"

          # Parse the Dockerfile to get the Node.js version
          DOCKER_NODE_VERSION=v$(cat Dockerfile \
              | grep 'FROM node:' \
              | head -n 1 \
              | sed -E 's/FROM node:([^ ]+).*/\1/')

          echo "docker-node-version=$DOCKER_NODE_VERSION" | tee -a "$GITHUB_OUTPUT"

          if [[ "$CURRENT_NODE_VERSION" == "$DOCKER_NODE_VERSION" ]]; then
              echo "Node version is already up to date."
              echo "needs-update=false" >> $GITHUB_OUTPUT
          else
              echo "Node version needs to be updated."
              echo "needs-update=true" >> $GITHUB_OUTPUT
          fi
      -
        uses: actions/setup-node@v5
        if: steps.check-versions.outputs.needs-update == 'true'
        with:
          node-version: ${{ steps.check-versions.outputs.docker-node-version }}
          cache: npm
          cache-dependency-path: docker-quicktype/package-lock.json
      -
        name: Update project Node version
        if: steps.check-versions.outputs.needs-update == 'true'
        working-directory: docker-quicktype
        env:
          TARGET_VERSION: ${{ steps.check-versions.outputs.docker-node-version }}
        run: |
          echo "${TARGET_VERSION}" > .nvmrc
          npm i
      -
        name: Check for node version changes
        id: node-version-changes
        run: |
          git status -s

          if [ -n "$(git status -s)" ]; then
            echo "detected=true" | tee -a "$GITHUB_OUTPUT"
          else
            echo "detected=false" | tee -a "$GITHUB_OUTPUT"
          fi
      -
        name: Commit node version changes if detected
        if: ${{ steps.node-version-changes.outputs.detected == 'true' }}
        uses: planetscale/ghcommit-action@v0.2.17
        env:
          GITHUB_TOKEN: ${{ steps.bot-token.outputs.token }}
        with:
          commit_message: "🤖 use node ${{ steps.check-versions.outputs.docker-node-version }}"
          repo: ${{ github.repository }}
          branch: ${{ github.head_ref || github.ref_name }}
      -
        name: Fail if changes
        if: ${{ steps.node-version-changes.outputs.detected == 'true' }}
        run: exit 1
      -
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker
      -
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/quicktype
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=pr
      -
        name: Determine image tag
        id: image-tag
        env:
          INPUT_PUSH: ${{ inputs.PUSH }}
          IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/quicktype
          IMAGE_TAG: ""
        run: |
          if [[ "$INPUTS_PUSH" == "true" ]]; then
            if [[ "$GITHUB_REF_TYPE" == "tag" ]]; then
              IMAGE_TAG="$GITHUB_REF_NAME"
            else
              >&2 echo "Can only push from tags"
              exit 1
            fi
          else
            IMAGE_NAME="local-quicktype"
            IMAGE_TAG="latest"
          fi

          echo "tag=$IMAGE_TAG" | tee -a "$GITHUB_OUTPUT"
          echo "slug=$IMAGE_NAME:$IMAGE_TAG" | tee -a "$GITHUB_OUTPUT"
      -
        uses: docker/build-push-action@v6
        id: docker-build
        with:
          context: ./docker-quicktype
          push: ${{ inputs.PUSH }}
          tags: ${{ steps.image-tag.outputs.slug }}
          labels: ${{ steps.meta.outputs.labels }}
      -
        name: Generate example
        working-directory: example
        run: |
          rm -rf outputs/*
          touch outputs/.gitkeep
          mkdir -p outputs/typescript
          mkdir -p outputs/golang
          
          echo "Generating TypeScript schemas"
          docker run \
            -v "$(pwd):/example" \
            "${{ steps.image-tag.outputs.slug }}" \
              --src-lang schema \
              --src "/example/inputs/jsonschema" \
              --lang typescript \
              --out "/example/outputs/typescript/index.ts" \
              --top-level "Models"

          echo "Generating Go schemas"
          docker run \
            -v "$(pwd):/example" \
            "${{ steps.image-tag.outputs.slug }}" \
              --src-lang schema \
              --src "/example/inputs/jsonschema" \
              --lang go \
              --out "/example/outputs/golang/models.go" \
              --package model \
              --field-tags json,dynamodbav \
              --top-level "Models"
      -
        name: Check for example changes
        id: example-changes
        run: |
          git config --global \
            "user.name" "github-actions[bot]"

          git config --global \
            "user.email" "github-actions[bot]@users.noreply.github.com"

          git add .
          git status -s

          if [ -n "$(git status -s)" ]; then
            echo "detected=true" | tee -a "$GITHUB_OUTPUT"
          else
            echo "detected=false" | tee -a "$GITHUB_OUTPUT"
          fi
      -
        name: Commit example changes if detected
        if: ${{ steps.example-changes.outputs.detected == 'true' }}
        uses: planetscale/ghcommit-action@v0.2.17
        env:
          GITHUB_TOKEN: ${{ steps.bot-token.outputs.token }}
        with:
          commit_message: "🤖 re-generate example"
          repo: ${{ github.repository }}
          branch: ${{ github.head_ref || github.ref_name }}
          file_pattern: example/outputs
      -
        name: Fail if changes
        if: ${{ steps.example-changes.outputs.detected == 'true' }}
        run: exit 1
