name: docker-build

on:
  workflow_call:
    inputs:
      CHECKOUT_REF:
        required: false
        type: string
      PUSH:
        required: true
        type: boolean
    secrets:
      BOT_APP_ID:
        required: true
      BOT_PRIVATE_KEY:
        required: true

permissions:
  contents: read
  id-token: write

defaults:
  run:
    shell: bash

env:
  GOPRIIVATE: github.com/chinesecheckers/*

jobs:

  build:
    name: ${{ inputs.PUSH && 'build-and-push' || 'build' }}
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - 
        name: Generate bot token
        id: bot-token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_PRIVATE_KEY }}
      -
        uses: actions/checkout@v5
        with:
          token: ${{ steps.bot-token.outputs.token }}
          ref: ${{ inputs.CHECKOUT_REF || github.ref }}
          fetch-depth: 0
      -
        uses: docker/setup-buildx-action@v3
      -
        if: ${{ inputs.PUSH }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ steps.bot-token.outputs.token }}
      -
        name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/quicktype
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha
      -
        uses: docker/build-push-action@v5
        with:
          context: ./docker-quicktype
          push: ${{ inputs.PUSH }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      