name: pr

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:

  detect-changes:
    uses: ./.github/workflows/detect-changes.yml
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    secrets: inherit

  check-source:
    permissions: write-all
    needs: detect-changes
    if: |
      needs.detect-changes.outputs.source-changed == 'true' ||
      needs.detect-changes.outputs.ci-changed == 'true'
    uses: ./.github/workflows/check-source.yml
    secrets: inherit

  pr-ready:
    if: always()
    needs:
      - detect-changes
      - check-source
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      id-token: write
    steps:
      -
        name: Validate jobs
        if: ${{ contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'failure') }}
        run: |
          echo "::error title=${{ github.workflow }}::at least one job failed or cancelled"
          exit 1
