name: release

run-name: ${{ github.ref_name }}

on:
  push:
    tags:
      - 'v*'

  workflow_dispatch:
    inputs:
      PUSH:
        description: Push the image?
        type: boolean
        default: true


permissions: write-all

defaults:
  run:
    shell: bash

jobs:

  release:
    name: release (${{ github.ref_name }})
    permissions: write-all
    uses: ./.github/workflows/docker-build.yml
    with:
      PUSH: true
    secrets: inherit
